name: focus_browser
description: A minimalist dark browser with sing-box VPN support

publish_to: 'none'

version: 1.0.4+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_windows: ^0.4.0
  cupertino_icons: ^1.0.8
  process: ^5.0.2
  path: ^1.9.0
  http: ^1.2.0
  logging: ^1.2.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
