# Generated platform build configuration.
# This file is generated by the Flutter tool.

set(FLUTTER_ROOT "/usr/local/flutter" CACHE STRING "Flutter SDK root")
set(PROJECT_DIR "/home/tannim/hz" CACHE STRING "Flutter project directory")
set(FLUTTER_TARGET "lib/main.dart" CACHE STRING "Flutter target entrypoint")
set(DART_DEFINES "" CACHE STRING "Dart defines")
set(DART_OBFUSCATION FALSE CACHE BOOL "Dart obfuscation")
set(TRACK_WIDGET_CREATION TRUE CACHE BOOL "Track widget creation")
set(TREE_SHAKE_ICONS FALSE CACHE BOOL "Tree shake icons")
set(PACKAGE_CONFIG ".dart_tool/package_config.json" CACHE STRING "Package config")
