name: Build Lightweight Browser with VLESS VPN

on:
  push:
    paths:
      - 'src/**'
      - 'main.py'
      - 'config/vless.txt'
      - 'resources/bookmarks.json'
      - '.github/workflows/build.yml'
      - 'requirements.txt'
  pull_request:
    paths:
      - 'src/**'
      - 'main.py'
      - 'config/vless.txt'
      - 'resources/bookmarks.json'
      - '.github/workflows/build.yml'
      - 'requirements.txt'

jobs:
  build:
    runs-on: windows-2022
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Download Xray-core
        run: |
          powershell -Command "Invoke-WebRequest 'https://github.com/XTLS/Xray-core/releases/latest/download/Xray-windows-64.zip' -OutFile xray.zip"
          powershell -Command "Expand-Archive -Path xray.zip -DestinationPath xray-temp"
          powershell -Command "Move-Item xray-temp/xray.exe bin/xray.exe -Force"
          Remove-Item xray.zip, xray-temp -Recurse -Force

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --add-data "config;config" --add-data "resources;resources" --add-data "bin;bin" main.py

      - name: Prepare release package
        run: |
          New-Item -ItemType Directory -Path "release" -Force
          Copy-Item "dist/main.exe" "release/lightweight-browser-vless.exe"
          Copy-Item "README.md" "release/"
          Copy-Item "config/vless.txt" "release/vless.txt"

      - name: Create release archive
        run: |
          Compress-Archive -Path "release/*" -DestinationPath "lightweight-browser-vless-windows.zip"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: lightweight-browser-vless-windows
          path: lightweight-browser-vless-windows.zip
          retention-days: 90
